- hosts: server
  become: yes
  become_method: sudo


  tasks:
    - name: docker compose down
      docker_compose:



- hosts: client
  become: yes
  become_method: sudo

  tasks:
    - name: docker compose down
      docker_compose:


- hosts: gateway
  become: yes
  become_method: sudo

  tasks:
    - name: docker compose down
      docker_compose:

    