- hosts: server
  become: yes
  become_method: sudo


  tasks:
    - name: Stopping containers
      docker_container:
        state: stopped
        all_containers: yes

    - docker_host_info:
        images: yes
        containers: yes
      register: docker_objects

    - docker_container:
        name: "{{ item.Id }}"
        state: absent
      loop: "{{ docker_objects.containers }}"
      loop_control:
        label: "{{ item.Id }}"

    - docker_image:
        name: item.RepoTags | first
        state: absent
        force_absent: yes
      loop: "{{ docker_objects.images }}"
      loop_control:
        label: "{{ item.RepoTags | first }}"



- hosts: client
  become: yes
  become_method: sudo

  tasks:
    - name: Stopping containers
      docker_container:
        state: stopped
        all_containers: yes

    - docker_host_info:
        images: yes
        containers: yes
      register: docker_objects

    - docker_container:
        name: "{{ item.Id }}"
        state: absent
      loop: "{{ docker_objects.containers }}"
      loop_control:
        label: "{{ item.Id }}"

    - docker_image:
        name: item.RepoTags | first
        state: absent
        force_absent: yes
      loop: "{{ docker_objects.images }}"
      loop_control:
        label: "{{ item.RepoTags | first }}"


- hosts: gateway
  become: yes
  become_method: sudo

  tasks:
    - name: Stopping containers
      docker_container:
        state: stopped
        all_containers: yes

    - docker_host_info:
        images: yes
        containers: yes
      register: docker_objects

    - docker_container:
        name: "{{ item.Id }}"
        state: absent
      loop: "{{ docker_objects.containers }}"
      loop_control:
        label: "{{ item.Id }}"

    - docker_image:
        name: item.RepoTags | first
        state: absent
        force_absent: yes
      loop: "{{ docker_objects.images }}"
      loop_control:
        label: "{{ item.RepoTags | first }}"

    